(define (problem pb1)
  (:domain Bellhop)

  (:objects
    floor0 floor1 floor2 lift - floor
	room1 room2 room3 room4 room5 room6 hall0 hall1 hall2 storage - room
	door0 door1 door2 door3 - door
	bag1 bag2 bag3 bag4 bag5 bag6 - bag
	Bellhop - robot
	sw1 sw2 sw3 sw4 sw5 sw6 - switch
  )
  (:init
	(in room1 floor1)
	(in room2 floor1)
	(in room3 floor1)
	(in room4 floor2)
	(in room5 floor2)
	(in room6 floor2)
	(in storage floor0)
	(in hall0 floor0)
	(in hall1 floor1)
	(in hall2 floor2)
	(in hall0 lift)
	(in hall1 lift)
	(in hall2 lift)
	(at sw1 room1)
	(at sw2 room2)
	(at sw3 room3)
	(at sw4 room4)
	(at sw5 room5)
	(at sw6 room6)
	(at door3 storage)
	(at door0 hall0)
	(at door1 hall1)
	(at door1 room1)
	(at door1 room2)
	(at door1 room3)
	(at door2 hall2)
	(at door2 room4)
	(at door2 room5)
	(at door2 room6)
	(at Bellhop storage)
	(at bag1 storage)
	(at bag2 storage)
	(at bag3 storage)
	(at bag4 storage)
	(at bag5 storage)
	(at bag6 storage)
	(same room1 room1)
	(same room2 room2)
	(same room3 room3)
	(same room4 room4)
	(same room5 room5)
	(same room6 room6)
	(same hall0 hall0)
	(same hall1 hall1)
	(same hall2 hall2)
	(empty Bellhop)
  )
  
  (:goal (and
    (light sw3)
    (at bag3 room3)
    (at bag1 room1)
    (at Bellhop storage))
  )
)